type: mpc
mpc:
  model_name: panda
  n: 7
  time_horizon: 20
  time_step: 0.05
  slack: False
  interval: 1
  weights:
    w: 3.0
    wvel: 1.0
    ws: 1e10
    wu: 0.1
    wobst: 0.00
  number_obstacles: 1
robot:
  collision_links: 
    - 'panda_link3'
    - 'panda_link5'
    - 'panda_link7'
  selfCollision:
    pairs:
      -
        - 'panda_link3'
        - 'panda_link7'
  urdf_file: panda_fk.urdf
  root_link: panda_link0
  end_link: panda_link8
  base_type: holonomic
